spring:
  application:
    name: aiservice

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: airecommendationfitness

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
